### ISSUE TITLE
adapt to 4.x?

### ISSUE THREAD

**Issue by gainskills** [S2Innovation/redmine_azure_ad#1]
Thank for your effort on project. I tried this plugin on Redmine4.1.0 + PG12 + docker

Got the error when Redmine is booting up:
```
redmine_1     | Gems in the groups development and test were not installed.
redmine_1     | Bundled gems are installed into `/usr/local/bundle`
redmine_1     | rake aborted!
redmine_1     | LoadError: cannot load such file -- omniauth
redmine_1     | /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
redmine_1     | /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
redmine_1     | /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
redmine_1     | /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
redmine_1     | /usr/src/redmine/plugins/redmine_azure_ad/init.rb:1:in `<top (required)>'
redmine_1     | /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
redmine_1     | /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
redmine_1     | /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
redmine_1     | /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
redmine_1     | /usr/src/redmine/lib/redmine/plugin.rb:181:in `block in load'
redmine_1     | /usr/src/redmine/lib/redmine/plugin.rb:172:in `each'
redmine_1     | /usr/src/redmine/lib/redmine/plugin.rb:172:in `load'
redmine_1     | /usr/src/redmine/config/initializers/30-redmine.rb:20:in `<top (required)>'
redmine_1     | /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `load'
redmine_1     | /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `block in load'
redmine_1     | /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
redmine_1     | /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `load'
redmine_1     | /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/engine.rb:663:in `block in load_config_initializer'
redmine_1     | /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/notifications.rb:170:in `instrument'
redmine_1     | /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/engine.rb:662:in `load_config_initializer'
redmine_1     | /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
redmine_1     | /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/engine.rb:619:in `each'
redmine_1     | /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/engine.rb:619:in `block in <class:Engine>'
redmine_1     | /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `instance_exec'
redmine_1     | /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `run'
redmine_1     | /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'
redmine_1     | /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/initializable.rb:50:in `each'
redmine_1     | /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/initializable.rb:50:in `tsort_each_child'
redmine_1     | /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/initializable.rb:60:in `run_initializers'
redmine_1     | /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/application.rb:361:in `initialize!'
redmine_1     | /usr/src/redmine/config/environment.rb:16:in `<top (required)>'
redmine_1     | /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/application.rb:337:in `require'
redmine_1     | /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/application.rb:337:in `require_environment!'
redmine_1     | /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
redmine_1     | /usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
redmine_1     | Tasks: TOP => db:migrate => db:load_config => environment
redmine_1     | (See full trace by running task with --trace)
redmine_1     | Bundler can't satisfy your Gemfile's dependencies.
redmine_1     | Install missing gems with `bundle install`.
```

**Comment by mliszcz** [comment]
Hi!
Sorry for the huge delay in response. We stopped using Redmine some time ago so we do not actively maintain this plugin. IIRC we were using this plugin with Redmine 4.0 and MySQL 5.7 (Bitnami stack).

I have a very limited knowledge of Redmine and Ruby in general but judging from your stacktrace rake/bundler cannot load `omniauth`. It is a hard dependency for this plugin to work. Have you installed `omniauth` into your Redmine environment, as README suggests?

**Comment by gainskills** [comment]
> Hi!
> Sorry for the huge delay in response. We stopped using Redmine some time ago so we do not actively maintain this plugin. IIRC we were using this plugin with Redmine 4.0 and MySQL 5.7 (Bitnami stack).
> 
> I have a very limited knowledge of Redmine and Ruby in general but judging from your stacktrace rake/bundler cannot load `omniauth`. It is a hard dependency for this plugin to work. Have you installed `omniauth` into your Redmine environment, as README suggests?

@mliszcz Thank a lot for pointing this out, will share if it works after I try it later.

**Comment by gainskills** [comment]
> Hi!
> Sorry for the huge delay in response. We stopped using Redmine some time ago so we do not actively maintain this plugin. IIRC we were using this plugin with Redmine 4.0 and MySQL 5.7 (Bitnami stack).
> 
> I have a very limited knowledge of Redmine and Ruby in general but judging from your stacktrace rake/bundler cannot load `omniauth`. It is a hard dependency for this plugin to work. Have you installed `omniauth` into your Redmine environment, as README suggests?

The Redmine works per your suggestion.
1. As you mentioned, install the dependencies 'omniauth-azure-activedirectory'
2. Register app on Azure, 
    Enable token authentication
    ![image](https://user-images.githubusercontent.com/1937472/73825675-4d0dd080-4861-11ea-8cbb-a4705066dcca.png)

    Note: without this step, it prompts the error: `AADSTS70005: response_type 'id_token' is not enabled for the application`
    ![image](https://user-images.githubusercontent.com/1937472/73825879-abd34a00-4861-11ea-9e6c-dfb5f6d7452a.png)

    Call back URL:
    ![image](https://user-images.githubusercontent.com/1937472/73825590-1cc63200-4861-11ea-9d98-f7bea31fc717.png)

Seems that MS OAuth will compare the reply URL, my question is how the URL is generated in the plugin for comparison?

I got an error: `AADSTS50011: The reply address does not match the reply addresses configured for the application.` in my environment: I mapped Redmine port 3000 to 80.

Thanks again,

**Comment by mliszcz** [comment]
This configuration has been working for us.:
* ID token authentication: enabled (just like you did)
* Token configuration (preview): empty list of claims
* Redirect URL set to: `https://<our-domain>/auth/azureactivedirectory/callback`

Since you are saying that Azure SSO rejects the request due to incorrect reply URL, I suggest to check the following:
* protocol (HTTP vs HTTPS)
* hostname - maybe you should have your IP or FQDN here
* port - you should use the one visible to the Redmine server, as this is where redirect URL is generated.

Redirect URL is generated by [omniauth-azure-activedirectory](https://github.com/AzureAD/omniauth-azure-activedirectory).

I do not have any running instance of Redmine to chcek, but I think you should be able to see the redirect URL in network inspector in your browser.
1. Clear cache / cookies just in case
1. Open the developer tools (network tab)
1. In Redmine, click on "Sign in with Azure AD"
1. You should see GET to `/auth/azureactivedirectory`
1. Then you should see GET to Microsoft SSO webpage and redirect URL should be in query string or inside the request body.

**Comment by gainskills** [comment]
Mliszcz, Thanks for your help with this.
My Redmine instance is running over Docker, the TCP 3000 port was mapped to 80, that's why I got the issue. and I agree with you that the issue can be resolved, e.g. changing Redmine to 80 so that the port mapping configuration can be removed.
